_target_: src.models.ae_module.AutoencoderKL

encoder:
  _target_: src.models.components.ae.SimpleConvEncoder
  levels: 3

decoder:
  _target_: src.models.components.ae.SimpleConvDecoder
  levels: 3

unet_regr:
  _target_: src.models.unet_module.UnetLitModule
  net:
    _target_: src.models.components.unet.DownscalingUnet
    in_ch: 32
    out_ch: 1
    features: [64,128,256,512]
  loss: 
    _target_: torch.nn.MSELoss
    reduction: mean
  optimizer: None
  # ckpt_path: '/home/gabriele/Documents/fbk/icsc/downscaling-hydra/logs/train/runs/2024-01-24_08-56-56/checkpoints/epoch_041.ckpt'
ae_flag: 'residual'
